- name: Restart compose
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail
      chmod +x docker_pre_build.sh
      # ./docker_pre_build.sh > docker_pre_build.log 2>&1
      sudo docker compose down || :
      sudo docker compose up -d
    chdir: "{{ frpclient_dir }}"
  changed_when: true
  async: 60
  poll: 5
  ignore_unreachable: true
