cloudflare_tunnel_token: ENC[AES256_GCM,data:mRZjVdG7r81z6q68BxSW95lLW+J7w70afnHEZ1VUjVj6Hvi5dw2UbDVDAHRFkK/D6ahalIqMW+9thyFQlWey1+NFT6Vy+Xvb1mbdkpK2NsK+tyLxDUABLVohMXtlY8JI/O1ss/Obz4Dn7td3mO3eR2txPfO65Qi8wUFXiEprjf2yCJqu4AQmN9SQAqxx7gXGlfl8QAbpACwRw3sFwF8YYwGpft7g1FZvrBZz+RElJrkY6TvC+Rb5Bw==,iv:vrBMipmv3s79HOTMSETuawfzZYZChzaJdyriM0Ulha4=,tag:4V7TiuXu5Ahxw/sMTqx7AA==,type:str]
frp_web_server_password: ENC[AES256_GCM,data:mAwrfEFTw5+tAG+IHcyAt4I/,iv:VosoFb+MNPAcFniMbuP+28q80It6hox8VCMomEzEVow=,tag:YLNFXW0Q4EBdTGkZ3XTkYQ==,type:str]
frp_auth_token: ENC[AES256_GCM,data:33vnAV9fDWDBY5QON6Nii4xVP1lYA8GZ,iv:uuZpMw+K/a84DOR/+bKI2G+of40a3sdReuF8grQdD0Q=,tag:akJZ5luULuzqhQIIH6wEmA==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/kizuna-org/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-16T05:15:46Z"
          enc: CiQAGOg4RfucpRGJD2OpwE4oY6kl8d5Xv3ukGGur1gIOUHQUXXcSSQClg6WHQqGtl0TYzaeWtvXipHS6qnftvWGKckmnW4UuZsDwLzKfXC6nOITCf3IxwtcO04Ary7o0CKYGa6Az3LyODx0Y1NRjlF8=
    lastmodified: "2025-11-16T05:15:47Z"
    mac: ENC[AES256_GCM,data:jSBn9Ug4KtOwNpUSIkC2A7LsOnU+4R7+89C6lbOrzuL8UDXT4+TEQ2oMaovUTHI0Mat/cWeTg3r8wN9VvhzkVBv2UZK3GtcKRTWepYQfCT6smH1hJPV7IIarWOnRLu3HJQlk2KxyZ72YC1CZHeZpypQwH0lHiNx3M9yr0UD7Jvs=,iv:wd8GRTatYWGEByTHXhDJd5roHGmcD1lJ9EOIClJkK3E=,tag:FmgyEJ6Ohp6lzmBvOP0jEg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
