cloudflare_tunnel_token: ENC[AES256_GCM,data:z1uuCtWTvhQq6Vg7uZ9jwe6aTvUgeEuTqlYbvAwn1YYolNqibv0Jkw2Gso1VRKNHilFZVaJZLcmR3wZTKmffZy7emj80mJqdIlriSwkKXVy+gLB55jSGA7jUy9ULuhDzBGyUQL/EuOCjVmL+8tf0bq8TAWxIcxdTxj3etE75Lkc1PNJW2KPuYHqsqx4fRNdgB+PEHue+T1Ee3DRHa7asNUpV8Ej/rlHcoYW46/oFwRA/ZPICrH4EfQ==,iv:MLzteu3lsU65IX5OsNob8WSPL2yQzRIkZDBRbEysKPU=,tag:laX57kLFlHSk4d1NLeswqg==,type:str]
frp_web_server_password: ENC[AES256_GCM,data:GNtcoa729ncdJ4iGr2GI6Knk,iv:KvqbR+sVhciIxGlwBYTUCY4StUYNgWRtXvrm67GVC0k=,tag:LX9mDATjH7xku8RWM5dAFg==,type:str]
frp_auth_token: ENC[AES256_GCM,data:lSymw+TgEpv+VHeasr8oxbcF1KHxuYW0,iv:kS65Hf9UeJCnuxT7TrLTYFIBUL2cTa+O6d8Fkv5DCOY=,tag:Zr1mi5U+3phU2iExlzE+sg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/kizuna-org/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-15T14:33:45Z"
          enc: CiQAGOg4RdiVQOur+TgA+wYhDdmdcPk8ecQ5o60b+kucRPd9olsSSQClg6WHjg7YyaHh3UkuikBpKqI3Sl5EM8Hd/fR6EQuEj8lRIDb95GJQ+92pcagGFhy+goYSdoJ86UxUAPkVLYfAOIaAMyt4PCY=
    lastmodified: "2025-11-15T14:33:45Z"
    mac: ENC[AES256_GCM,data:uaZemnOhw1pErYoj2pNaYNbC23QyospY5fQxT4pu+SG+qtsHEP2RibMG9lggX2LYu0vAXfnI4fW+UVDcZBFU4E2urUuDIRuFpJHPkJYJ5O4y9kbQBqbIoL6iigSRJehGrs187HpV0wN1nexdzZtrQLGtlK4j0pxNRFu56W1lBRg=,iv:/ZqFMhNK/5OmjbFtigD+815j9RmQZ3zJen0/gyquXoc=,tag:GR/KgKI39J/3pwSS4KSn8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
