auth_token: ENC[AES256_GCM,data:/hQpOWJtjHcUKY5ITCXS//efDlkviMT5,iv:hnAbuMyeZyfyeuQWuLAMDLNizpj00ekC36D7qP5KQGg=,tag:Iy1pn7zIYVjFAqGoMemZcQ==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/kizuna-org/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-16T05:15:47Z"
          enc: CiQAGOg4RQnFkG6U3DoJEYMGAaWLSxd/Dx1fmVh/xVi/SukfabUSSQClg6WHkIt65ekw4i4ZLUvGS84BJ40wQJUug4/hA/5Iy6aObVDruMvYL3Fa/RqWysTCb4zGqRWmW0WzpM9hH70Lj/WAJo6E+rU=
    lastmodified: "2025-11-16T05:15:47Z"
    mac: ENC[AES256_GCM,data:tZxgEYHrA7nVhcHyQeWAA//mSZG7e0LMraGktm9LCa+ZguDncfiH191F4P8RJX5CCdzqA1f00EP3P1uAcYK9cMWrUuJ9fp9jscEAmyy27v7HdNIe8frF/wcNuPbGSWUaVDmOd7sN6sMlODELG6x031FryT+yx5jwVqPbgZbDaqE=,iv:3N+tWnoppSWOrdluLnISgYvAt9K67bt+KTWFF9bg6n4=,tag:XIT5r+Aoz5gKJVaw4Z8hFA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
