- name: Setup kind cluster
  hosts: edu-gpu
  gather_facts: true
  roles:
    - kind
    - argocd

- name: Deploy frp docker compose
  hosts: snct-proxy-srv.shiron.dev
  gather_facts: true
  roles:
    - frp

- name: Deploy frp client
  hosts: edu-gpu-2
  gather_facts: true
  roles:
    - frpc
